# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 450)
        MainWindow.setStyleSheet("QPlainTextEdit {\n"
"    border: 1px solid lightgrey;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.boton = QtWidgets.QPushButton(self.centralwidget)
        self.boton.setGeometry(QtCore.QRect(75, 360, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.boton.setFont(font)
        self.boton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton.setStyleSheet("")
        self.boton.setObjectName("boton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(25, 130, 300, 40))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.txt2 = QtWidgets.QLabel(self.centralwidget)
        self.txt2.setGeometry(QtCore.QRect(25, 190, 300, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.txt2.setFont(font)
        self.txt2.setObjectName("txt2")
        self.textEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(25, 230, 300, 40))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit.setOverwriteMode(False)
        self.textEdit.setPlaceholderText("")
        self.textEdit.setObjectName("textEdit")
        self.res32 = QtWidgets.QLabel(self.centralwidget)
        self.res32.setGeometry(QtCore.QRect(25, 280, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.res32.setFont(font)
        self.res32.setText("")
        self.res32.setAlignment(QtCore.Qt.AlignCenter)
        self.res32.setObjectName("res32")
        self.txt1 = QtWidgets.QLabel(self.centralwidget)
        self.txt1.setGeometry(QtCore.QRect(25, 90, 300, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.txt1.setFont(font)
        self.txt1.setObjectName("txt1")
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(75, 20, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.titulo.setFont(font)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.res64 = QtWidgets.QLabel(self.centralwidget)
        self.res64.setGeometry(QtCore.QRect(25, 310, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.res64.setFont(font)
        self.res64.setText("")
        self.res64.setAlignment(QtCore.Qt.AlignCenter)
        self.res64.setIndent(1)
        self.res64.setObjectName("res64")
        self.boton.raise_()
        self.comboBox.raise_()
        self.textEdit.raise_()
        self.res32.raise_()
        self.txt1.raise_()
        self.titulo.raise_()
        self.txt2.raise_()
        self.res64.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boton.setText(_translate("MainWindow", "CONVERTIR"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Binario a Decimal"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Binario Complemento 1 a Decimal"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Binario Complemento 2 a Decimal"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Binario IEEE754 (32 bits) a Decimal"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Binario a Octal"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Binario a Hexadecimal"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Decimal a Binario"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Decimal a Binario Complemento I"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Decimal a Binario Complemento II"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Decimal a Binario IEEE754 (32 bits) "))
        self.comboBox.setItemText(10, _translate("MainWindow", "Decimal a Octal"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Decimal a Hexadecimal"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Octal a Binario"))
        self.comboBox.setItemText(13, _translate("MainWindow", "Octal a Decimal"))
        self.comboBox.setItemText(14, _translate("MainWindow", "Hexadecimal a Binario"))
        self.comboBox.setItemText(15, _translate("MainWindow", "Hexadecimal a Decimal"))
        self.txt2.setText(_translate("MainWindow", "Ingresa el numero"))
        self.txt1.setText(_translate("MainWindow", "Selecciona el metodo"))
        self.titulo.setText(_translate("MainWindow", "Calculadora"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

